### ISSUE TITLE
How to update ImGui to latest docking branch?

### ISSUE THREAD

**Issue by hippyau** [juliettef/RCCpp-DearImGui-GLFW-example#1]
Hi, 

 This is very cool,  i'd like to use to speed up development of ImGui code for a separate application, but I would like to use the new tables API and the docking branch.  Ideally I'd like an easy way to 'turn on / off' the RCCpp code entirely between debug and release, but I don't think that would be easy :)

So, to help with latest ImGui tables and docking, How can I update the ImGui submodule to the latest?

Cheers,

**Comment by dougbinks** [comment]
We added GLFW as a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), which can be treated in the same way as a git repo when from the command line when you are in the submodule directory. So if you ```cd imgui``` you can then run git commands to pull/checkout etc.

To [disiable RCCpp see the documentation](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Disabling-runtime-compilation). Basically if you define ```RCCPPOFF``` in a build it will disable RCCpp, but you can also disable/enable it at runtime using ```RuntimeObjectSystem::SetAutoCompile```.

**Comment by hippyau** [comment]
Awesome,  thanks so much!
