### ISSUE TITLE
Does RCCpp work with DLLs?

### ISSUE THREAD

**Issue by Platforming-Mayhem** [juliettef/RCCpp-DearImGui-GLFW-example#2]
I was wondering if this only works with .exe applications or if it also works when the RCCppMainloop.cpp is in a dll

**Comment by dougbinks** [comment]
RCC++ can work with the runtime compiled code in a DLL, but I don't have any examples of this. Note that the main project website for RCC++ is here: https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus

**Comment by Platforming-Mayhem** [comment]
thanks :)
